# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersinfo',
            table='usersInfo',
        ),
    ]
