# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170913_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicId', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.AlterModelTable(
            name='usersinfo',
            table='users',
        ),
        migrations.AddField(
            model_name='topics',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UsersInfo'),
        ),
    ]
