# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170916_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='userId',
            new_name='user',
        ),
    ]
