# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170916_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapId', django.contrib.postgres.fields.jsonb.JSONField()),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topics')),
            ],
            options={
                'db_table': 'topicMap',
            },
        ),
    ]
