# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_topicmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmap',
            name='topicId',
        ),
        migrations.DeleteModel(
            name='TopicMap',
        ),
    ]
