# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170920_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMap',
            fields=[
                ('mapDetails', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mapId', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topics')),
            ],
            options={
                'db_table': 'topicMap',
            },
        ),
    ]
