# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_topicmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmap',
            old_name='topicId',
            new_name='topic',
        ),
    ]
