# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 13:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170920_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('type', models.TextField()),
                ('data', models.TextField()),
                ('links', django.contrib.postgres.fields.jsonb.JSONField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topics')),
            ],
            options={
                'db_table': 'topicBook',
            },
        ),
    ]
